import random
from lists import *
_CHAPTER_LINE = '=' * 75
fighter_choice = ''
def assign_traits(main_personality_traits, num_traits=4):
    """this function generages a personality trait from the list...kinda
    useless change later"""
    return random.sample(main_personality_traits, num_traits)
def generate_character():
    """This function generates a fighter for use later when giving the user
    three options for fighters to train, assigning a name, weight, height,
    strength, and main personality trait to them for gameplay"""
    personality = assign_traits(main_personality_traits, 1)
    fname = random.choice(first_names)
    lname = random.choice(last_names)
    height = (possible_heights[random.randint(0, len(possible_heights) - 1)])
    weight = (random.randint(100, 205))
    speed = (random.randint(25, 100))
    power = (random.randint(25, 100))
    finesse = (random.randint(25, 100))
    strength = random.choice(strengths)
    return {
        'first_name': fname,
        'last_name': lname,
        'name': fname + ' ' + lname,
        'traits': personality,
        'weight': weight,
        'height': height,
        'speed': speed,
        'power': power,
        'finesse': finesse,
        'strength': strength
    }

def display_character(character):
    """This function creates a string that actually displays the
    characteristics generated by the generate_character function, and allows
    for displaying specific elements of the fighter to the user"""
    display_string = (
        f"Name: {character['name']}\n"
        f"Height: {character['height']}\n"
        f"Personality: {', '.join(character['traits'])}\n"
        f"Weight: {character['weight']} lbs\n"
        f"Strength: {character['strength']}\n"
    )
    return display_string

def calculate_win_percentage(fighter, opponent, strategy_modifier=0):
    power_advantage = (fighter['power'] - opponent['power']) / 100
    speed_advantage = (fighter['speed'] - opponent['speed']) / 100
    finesse_advantage = (fighter['finesse'] - opponent['finesse']) / 100
    win_probability = (
        (power_advantage * 0.4) +
        (speed_advantage * 0.3) +
        (finesse_advantage * 0.3) +
        strategy_modifier
    ) * 100
    win_probability += random.uniform(-5, 5)
    return max(0, min(100, win_probability))

fighter1 = generate_character()
fighter2 = generate_character()
fighter3 = generate_character()

tier1_opponent = generate_character()

print(_CHAPTER_LINE)
print("Welcome to Boxing Coach Simulator 20XX!")
print("""In this game, you'll take the role of a boxing coach looking to train
the next boxing champion in the division of your choosing!""")
user_enter = input("Press 'Enter' to begin -> ")
if user_enter == '':
    print(_CHAPTER_LINE)
    menu_input = input("""(A) -> Tutorial
(B) -> Start Game
(C) -> Credits\n""")
    menu_input = menu_input.upper()
    if menu_input == 'A':
        print("""In Boxing Coach Simulator 20XX, you take the role of a 
boxing coach. You will be given a choice between three fighters to choose as
your main pupil. These fighters will have many different stats that 
determine their ability to fight, such as their strengths, weaknesses, 
personality traits, and their 'weapon'. 
A weapon in the context of the game is a fighters main tool that they will 
use to win fights. For example, a 'ghost jab' is a weapon that will let a fighter
catch their opponent off-guard when they use it as they jab with blinding 
speed. You will be given choices to influence your fighter, and their 
success will depend on the way you train them. Carefully consider their 
personality, strengths, weaknesses, and weapons to lead your fighter to the 
champion title!""")
    if menu_input == 'B':
        print("""You enter the Noo-Boxers Gym, scoping out the potential 
fighters around you and trying to search for a prospect who looks promising. 
You spot three distinct fighters.""")
        print(_CHAPTER_LINE)
        print(display_character(fighter1))
        print(_CHAPTER_LINE)
        print(display_character(fighter2))
        print(_CHAPTER_LINE)
        print(display_character(fighter3))
        print(_CHAPTER_LINE)
        while fighter_choice not in ['1', '2', '3']:
            fighter_choice = input("Pick which fighter you'd like to take on! ")
            if fighter_choice == '1':
                fighter = fighter1
            elif fighter_choice == '2':
                fighter = fighter2
            elif fighter_choice == '3':
                fighter = fighter3
            else:
                print("Invalid choice! Try again.")
        print(f"You've chosen {fighter['name']} as your main pupil.")
        print(f"His speciality is {fighter['strength']}")
        def training_sequence():
            print(f"""As his fight approaches, {fighter['first_name']}needs guidance for his training.
He asks you what you think he should focus on. You ask him to demonstrate 
either his speed, strength, or finesse:
(SP) : Speed
(P) : Power
(F) : Finesse""")
            stat_demo = ''
            upgrade_stat = ''
            while stat_demo not in ['SP', 'P', 'F']:
                stat_demo = input("Choose which stat you would like to see: ")
                stat_demo = stat_demo.upper()
                if stat_demo == 'SP':
                    print(f"Speed = {fighter['speed']}")
                elif stat_demo == 'P':
                    print(f"Power = {fighter['power']}")
                elif stat_demo == 'F':
                    print(f"Finesse = {fighter['finesse']}")
            while upgrade_stat not in ['SP', 'P', 'F']:
                upgrade_stat = input(f"Now, choose which stat to work on with "
                                     f"{fighter['first_name']}: ")
                upgrade_stat = upgrade_stat.upper()
                if upgrade_stat == 'SP':
                    fighter['speed'] = fighter['speed'] + 5
                    print(f"New Speed = {fighter['speed']}")
                elif upgrade_stat == 'P':
                    fighter['power'] = fighter['power'] + 5
                    print(f"New Power = {fighter['power']}")
                elif upgrade_stat == 'F':
                    fighter['finesse'] = fighter['finesse'] + 5
                    print(f"New Finesse = {fighter['finesse']}")
        training_sequence()
        print(f"""After training, you do some scouting on 
{fighter['first_name']}'s first opponent. You see that their name is 
{tier1_opponent['name']} and their main strength is {tier1_opponent['strength']}.""")
        calculate_win_percentage(fighter, tier1_opponent)

    if menu_input == 'C':
        print(_CHAPTER_LINE)
        print("""This game was made by a solo dev named Preston Knoebel. It 
serves as his first personal project, and was made to express his 
love for the sport of boxing and a joy for simulation games.""")
